# Numpy

numpy is one of the most fundamental package in [scientific python stack](https://www.scipy.org/)
which consists os other packages like matplotlib, scipy, pandas, sympy and ipython.



It Provids following operations
- Fast vectorized mathematics operations.
- Common array algorithms like sorting, unique, and set operations
- Efficient descriptive statistics and aggregating/summarizing data and group-wise data manipulations
- Lot of other features. It is a big library

# Why we care about numpy
- It is designed for efficiency.
- Under the hood it stores data in contigous block of memory
- Algorithm written in c language can operate fast on data(no type checking etc.)
- Less memeory footprint compred to python object

# Is numpy fast comapred to basic python object. Really?


Let see first hand. 
Let's create  10000 interger in numpy and python list and compare time to add them

In [3]:
import numpy as np
max_num = 100000
arr_int = np.arange(max_num)
type(arr_int)
list_int = list(range(max_num))
%time  for _ in range(10): arr_int.sum()



CPU times: user 2.29 ms, sys: 0 ns, total: 2.29 ms
Wall time: 1.84 ms


In [5]:
from functools import reduce
%time for _ in range(10): reduce(lambda a,b : a*b, list_int)

CPU times: user 120 ms, sys: 0 ns, total: 120 ms
Wall time: 130 ms


# The NumPy ndarray: A Multidimensional Array Object

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. 
- One of the most fundamental object in numpy is ndarray or N-dimentional array abstraction.
- It support fast operation on vector, matrices and higher dimensional tensors.


In [6]:
# let check the type of earlier numpy arr of int
print(type(arr_int))
# it has size shape 
print(arr_int.shape)
# dtype(data type of the array)
print(arr_int.dtype)


<class 'numpy.ndarray'>
(100000,)
int64


## Creating ndarrays

In [7]:
np.array?

In [8]:
# by directly giving list of elements

arr1 = np.array([1, 3 ,5, 8.0])
print(arr1)

[1. 3. 5. 8.]


In [11]:
# create a two dimension arrar with first row 1.1 ,5 ,7 and second row 5, 10, 12 ?
# hint use list of list in array argument

arr = np.array([[1.1, 5 ,7], [5, 10, 12]])
print(arr)
print(type(arr))
print(arr.shape)

[[ 1.1  5.   7. ]
 [ 5.  10.  12. ]]
<class 'numpy.ndarray'>
(2, 3)


In [14]:
# print is shape and dtype?



# print dimension of this array. hint check it properties using . and tab
print(len(arr))

2


## is there other way to create  numpy array object?

In [18]:
np.ones(10, dtype= int)



array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
# for higher dimetional array pass shape as tuple
np.zeros((5, 4))
np.zeros?

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# handy way to create array of integer upto a maximum
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# create identity matrix of size 4x4 ??? 
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
# convert following array to float?
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(float)
arr



int64


array([1., 2., 3., 4., 5.])

## Arithmetic with NumPy Arrays

Any arithmetic operations between equal-size arrays applies the operation element-wise

In [29]:
arr = np.arange(1, 5, dtype=float).reshape((2,2))
arr

array([[1., 2.],
       [3., 4.]])

In [30]:
# let's multiply. element wise mulitplication as far as size matches
arr*arr

array([[ 1.,  4.],
       [ 9., 16.]])

In [31]:
# raise each element power of itself in the martix?

arr**arr

array([[  1.,   4.],
       [ 27., 256.]])

In [34]:
# how to do matrix multiplication?

print(arr)
print(np.matmul(arr, arr))
print(arr.dot(arr))

[[1. 2.]
 [3. 4.]]
[[ 7. 10.]
 [15. 22.]]
[[ 7. 10.]
 [15. 22.]]


## Basic Indexing and Slicing

In [36]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d

a = np.array([1,2])
b = np.array([2,5])
print(a.dot(b))

12


In [42]:
# slice first two row?
print(arr2d)
arr2d[0:2, :]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# slice 2 and 3rd row and second and third column

print(arr2d)
print(arr2d[1:3, 1:3])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


## Boolean Indexing

In [45]:
arr = np.random.randn(3, 4)
arr

array([[-0.46688732,  1.36160048, -1.03729746, -1.93448972],
       [-1.03712834, -1.53380474,  0.97776581, -0.51756079],
       [ 0.57173276, -0.60727595, -0.81264578, -1.03221859]])

In [48]:
# find all the values grater than .5
print(arr)
arr[arr>.5]

[[-0.46688732  1.36160048 -1.03729746 -1.93448972]
 [-1.03712834 -1.53380474  0.97776581 -0.51756079]
 [ 0.57173276 -0.60727595 -0.81264578 -1.03221859]]


array([1.36160048, 0.97776581, 0.57173276])

## Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.


In [49]:
arr2d = np.array([[2, 5 ,8],[ 10, 20, 30]])
print(arr2d)
print(arr2d[[1, 1], [ 0, 1]])



[[ 2  5  8]
 [10 20 30]]
[10 20]


## Views versus copies in NumPy

 View is another way of vewing same data.
**slicing creates view and fancy index doesn't createview**

In [50]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
aslice = a[1:4]
print(aslice)

[2 3 4]


In [52]:
a[1:4] = 20
print(aslice)

[20 20 20]


## Transposing Arrays and Swapping Axes

**note that swapaxes return view of data**

In [53]:
a = np.arange(12).reshape((3, 4))
print(a)
print('Transpose is')
## ???
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose is
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [54]:
#For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes 
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print('swapping axis (0, 1, 2) to (1, 0, 2) ')

print(arr.transpose((1, 0, 2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
swapping axis (0, 1, 2) to (1, 0, 2) 
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [55]:
#For 2d array T was same as swapaxes. For ndarray has the method swapaxes
print(arr)
print('after swapping axis 1 and 2')
### ????
arr.swapaxes(1,2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
after swapping axis 1 and 2


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions(ufun): Fast Element-Wise Array Functions

ufunc, is a function that performs element-wise operations on data in ndarrays
like **sqrt, exp , log, floor, isnan etc.** 

They can take more tan one array depnding on operation.

In [56]:
a = np.array([[1 ,4 ],[6, 9]])
np.sqrt(a)

array([[1.        , 2.        ],
       [2.44948974, 3.        ]])

## Array-Oriented Programming with Arrays 

Usng nd array we can write may task involving loops and simple array expression.



### Expressing Conditional Logic as Array Operations
numpy.where function is a vectorized version of the ternary expression x if condition else y

In [57]:
x = np.array([1, 3 ,5 ,7])
y = np.array([-4, -6, -7, -10])
cond = np.array([True, False, False, True])
np.where(cond, x, y)

array([ 1, -6, -7,  7])

In [59]:
arr= np.random.randn( 3,3)
print(arr)
## ? create a new array with element 1 if arr has positive element or -1 if array has negative element
np.where(arr > 0, 1, -1)

[[-0.7301239   0.23783468  0.08578282]
 [ 0.74549337 -0.93572007 -2.07607664]
 [ 0.71014369  0.19127268 -0.21726307]]


array([[-1,  1,  1],
       [ 1, -1, -1],
       [ 1,  1, -1]])

## Mathematical and Statistical Methods

In [61]:
arr = np.array([[1, 2 ,3], [4, 5 ,6]])
print(arr)

## print them mean along axis = 1, ????????
print(arr.mean(axis=1))

[[1 2 3]
 [4 5 6]]
[2. 5.]


In [63]:
arr = np.array([1 , 3 , 12 ,7, 9])
print(arr.cumsum())
print (arr.cumprod())



# extension for higher dimension existand and one can specify the axis to act along

[ 1  4 16 23 32]
[   1    3   36  252 2268]


In [64]:
## find the indcies of max element
print(arr)
print(arr.argmax())

[ 1  3 12  7  9]
2


## Methods for Boolean Arrays

**any, all and logical operator**.

Really helpful in writing algorithmic code where you need to check lot of path

In [67]:
arr = np.random.randint(-5, high = 10, size = 6)
print(arr)
## count number of negative element???
(arr< 0).sum()

[ 3 -5 -2  3  5 -1]


3

In [69]:
bool_arr= np.array([True, True, False, True])
## check if any elementis true??
bool_arr.any()

## check is all element are true
bool_arr.all()

False

## Sorting
similar to python builtin sort for list

In [ ]:
arr= np.array([3, -2 ,8 ,1, 5])
arr.sort()
print(arr)

print(arr[int(.5*len(arr))]) ## middle element

In [ ]:
## side
names = ['Moran' , 'Rosy'  , 'Eyerusalem', 'Marnie']
print(sorted(names))

## what if I want to sort by length, lower length first???


## Unique and Other Set Logic
Some operations for one dimensional array
**unique, intersect1d(x, y),  union1d(x, y) etc**

In [ ]:
names = np.array(['Moran' , 'Rosy'  , 'Eyerusalem', 'Marnie', 'Moran'])
print(np.unique(names))
## can you do it in pure python ??


## Linear Algebra
numpy.linalg has a standard set of matrix  operation(?). These are typically implemneted in BLAS, LAPCK, Intel MKL
library


In [ ]:
# inverse of  matrix
X = np.random.randn(4, 4)
X_inv = np.linalg.inv(X)
print(X.dot(X_inv))


In [ ]:
# svd. singluar value decomposition
a = np.random.randn(4,3)
u, s, vh = np.linalg.svd(a, full_matrices=True)
print(u.shape, s.shape, vh.shape)
np.linalg.svd?

In [ ]:
# let check if factorization is  true
np.allclose(a, np.dot(u[:,:3]*s, vh))

## Pseudorandom Number Generation
lots of function for drawing from normal, binmial, chisq, gamma, uniform distrubtion

## Example random walk

In [ ]:
# let similulate random walk with qual probalbility of step 1 or -1 in pure python
position = 0
walk = [0]
for i in range(100):
    step = 1 if np.random.choice([True, False]) else -1
    position += step
    walk.append(position)



In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(walk)

In [ ]:
#or using  numpy array we can do following
ranndrom_draw= np.random.choice?

In [ ]:
random_walk= np.random.choice([1, -1], size = 100)

In [ ]:
walk = random_walk.cumsum()
plt.plot(walk)

In [ ]:
# can ask lot of interesting statistics, like first time crossed 10, ???



Also look into
- Boradcasting in numpy
- [Scipy Lecture Notes](https://www.scipy-lectures.org/)